# Generated by Django 5.1.5 on 2025-05-24 22:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('IdCandidatura', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreCandidatura', models.CharField(default='')),
                ('TipoCandidatura', models.CharField(default='Simple')),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('IdCenso', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreCenso', models.CharField(default='', max_length=100)),
                ('Descripcion', models.CharField(default='', max_length=200)),
                ('nCensados', models.IntegerField()),
                ('FicheroAsociado', models.CharField(default='Ninguno')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('IdCertificado', models.IntegerField(primary_key=True, serialize=False)),
                ('TipoCertificado', models.CharField(default='Propio')),
                ('Fichero', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MesaElectoral',
            fields=[
                ('IdMesa', models.IntegerField(primary_key=True, serialize=False)),
                ('IdVotacion', models.IntegerField()),
                ('IdCertificado', models.IntegerField()),
                ('NombreMesa', models.CharField(default='')),
                ('Titular1', models.CharField(max_length=100)),
                ('IdTitular1', models.IntegerField()),
                ('Titular2', models.CharField(max_length=100)),
                ('IdTitular2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('IdNoticia', models.IntegerField(primary_key=True, serialize=False)),
                ('TituloNoticia', models.CharField(default='')),
                ('TextoNoticia', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('IdVotacion', models.IntegerField(primary_key=True, serialize=False)),
                ('TituloVotacion', models.CharField(max_length=100)),
                ('NParticipantes', models.IntegerField()),
                ('Resultado', models.CharField(default='Sin Resolver', max_length=11)),
                ('Estado', models.BooleanField(default=False)),
                ('BasesVotacion', models.FileField(upload_to='')),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=200)),
                ('DocumentoFiscal', models.CharField(max_length=12)),
                ('IdEncriptado', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('IdCertificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.certificado')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('IdVoto', models.IntegerField(primary_key=True, serialize=False)),
                ('hashVoto', models.CharField(default='')),
                ('IdVotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.votacion')),
            ],
        ),
    ]
