# Generated by Django 5.1.5 on 2025-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0002_alter_usuario_documentofiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='IdCensoRelacionada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noticias',
            name='IdVotacionRelacionada',
            field=models.IntegerField(default=0),
        ),
    ]
