# Generated by Django 5.1.5 on 2025-05-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0003_noticias_idcensorelacionada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='candidaturaVotada',
            field=models.IntegerField(default=0),
        ),
    ]
