# Generated by Django 5.1.5 on 2025-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0004_voto_candidaturavotada'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='NoticiaApp',
            field=models.BooleanField(default=False),
        ),
    ]
