# Generated by Django 5.1.5 on 2025-05-28 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0005_noticias_noticiaapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='candidaturaVotada',
        ),
        migrations.AddField(
            model_name='voto',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voto',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voto',
            name='nombreCandidatura',
            field=models.TextField(default=''),
        ),
    ]
