# Generated by Django 5.1.5 on 2025-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0006_remove_voto_candidaturavotada_voto_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='Fichero',
            field=models.FileField(upload_to=''),
        ),
    ]
