# Generated by Django 5.1.5 on 2025-05-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0007_alter_certificado_fichero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censo',
            name='FicheroAsociado',
            field=models.FileField(upload_to=''),
        ),
    ]
