# Generated by Django 5.1.5 on 2025-05-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0008_alter_censo_ficheroasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='IdCandidatura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='censo',
            name='IdCenso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='IdCertificado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mesaelectoral',
            name='IdMesa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='IdNoticia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='IdVotacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voto',
            name='IdVoto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
