# Generated by Django 5.2.1 on 2025-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0009_alter_candidatura_idcandidatura_alter_censo_idcenso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='Resultado',
            field=models.CharField(default='Sin Resolver', max_length=12),
        ),
    ]
