# Generated by Django 5.1.5 on 2025-06-02 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0010_alter_votacion_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('IdIncidencia', models.AutoField(primary_key=True, serialize=False)),
                ('TituloIncidencia', models.CharField()),
                ('IncidenciaSolucionada', models.BooleanField(default=False)),
                ('TextoIncidencia', models.CharField()),
                ('FicheroIncidencia', models.FileField(blank=True, null=True, upload_to='')),
                ('IdCenso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.censo')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IdVotacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.votacion')),
            ],
        ),
    ]
