# Generated by Django 5.1.5 on 2025-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0011_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='RespuestaAdministrador',
            field=models.TextField(blank=True, null=True),
        ),
    ]
