# Generated by Django 5.1.5 on 2025-06-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0012_incidencia_respuestaadministrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='IdEncriptado',
            field=models.CharField(max_length=64),
        ),
    ]
