# Generated by Django 5.1.5 on 2025-06-09 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0013_alter_usuario_idencriptado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatosNombrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.candidatura')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.votacion')),
            ],
            options={
                'unique_together': {('votacion', 'candidatura')},
            },
        ),
        migrations.CreateModel(
            name='CensoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.censo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'censo')},
            },
        ),
        migrations.CreateModel(
            name='CensoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.censo')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.votacion')),
            ],
            options={
                'unique_together': {('votacion', 'censo')},
            },
        ),
        migrations.CreateModel(
            name='InscritosVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.votacion')),
            ],
            options={
                'unique_together': {('usuario', 'votacion')},
            },
        ),
        migrations.CreateModel(
            name='IntegrantesCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.candidatura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'candidatura')},
            },
        ),
    ]
