# Generated by Django 5.1.5 on 2025-06-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0014_candidatosnombrados_censousuario_censovotacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaelectoral',
            name='IdTitular1',
        ),
        migrations.RemoveField(
            model_name='mesaelectoral',
            name='IdTitular2',
        ),
        migrations.RemoveField(
            model_name='mesaelectoral',
            name='Titular1',
        ),
        migrations.RemoveField(
            model_name='mesaelectoral',
            name='Titular2',
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='TipoCandidatura',
            field=models.CharField(choices=[('individual', 'Individual'), ('multiple', 'Múltiple')], max_length=10),
        ),
    ]
