# Generated by Django 5.1.5 on 2025-06-13 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0015_remove_mesaelectoral_idtitular1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrantesMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.mesaelectoral')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'mesa')},
            },
        ),
    ]
