# Generated by Django 5.1.5 on 2025-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0016_integrantesmesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaelectoral',
            name='Sorteada',
            field=models.BooleanField(default=False),
        ),
    ]
