# Generated by Django 5.1.5 on 2025-06-18 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0018_alter_mesaelectoral_idcertificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='Fichero',
        ),
        migrations.RemoveField(
            model_name='mesaelectoral',
            name='IdCertificado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='IdCertificado',
        ),
        migrations.AddField(
            model_name='certificado',
            name='clave_privada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='clave_publica',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificado',
            name='propietario_mesa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.mesaelectoral'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='propietario_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='TipoCertificado',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('mesa', 'MesaElectoral')], max_length=10),
        ),
    ]
