# Generated by Django 5.1.5 on 2025-06-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0019_remove_certificado_fichero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primera_vez',
            field=models.BooleanField(default=True),
        ),
    ]
