# Generated by Django 5.1.5 on 2025-06-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0021_remove_voto_nombrecandidatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='RecuentoAutorizado',
            field=models.BooleanField(default=False),
        ),
    ]
