# Generated by Django 5.2.1 on 2025-07-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0022_votacion_recuentoautorizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='Resultado',
            field=models.CharField(default='Sin Resolver', max_length=13),
        ),
    ]
