# Generated by Django 5.2.1 on 2025-11-25 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0024_alter_usuario_email_rolusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen_adjunto', models.ImageField(blank=True, null=True, upload_to='comunicaciones_director/')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
