# Generated by Django 5.2.1 on 2025-11-26 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0025_comunicaciondirector'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicaciondirector',
            name='candidatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.candidatura'),
        ),
        migrations.AddField(
            model_name='comunicaciondirector',
            name='votacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.votacion'),
        ),
    ]
