# Generated by Django 5.2.1 on 2025-11-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0026_comunicaciondirector_candidatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='fecha_revocacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='motivo_revocacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='revocado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mesaelectoral',
            name='certificado_visible',
            field=models.BooleanField(default=False),
        ),
    ]
