# Generated by Django 5.2.1 on 2025-12-16 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0027_certificado_fecha_revocacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicaciondirector',
            name='candidatura',
        ),
        migrations.RemoveField(
            model_name='comunicaciondirector',
            name='votacion',
        ),
        migrations.AddField(
            model_name='candidatosnombrados',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_campaña', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicaciondirector',
            name='campaña',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.candidatosnombrados'),
        ),
        migrations.AddConstraint(
            model_name='candidatosnombrados',
            constraint=models.UniqueConstraint(condition=models.Q(('director__isnull', False)), fields=('votacion', 'director'), name='unique_director_por_votacion'),
        ),
    ]
