# Generated by Django 5.2.1 on 2026-01-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0028_remove_comunicaciondirector_candidatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_no_modificacion', models.DateField()),
                ('fecha_censos', models.DateField()),
                ('duracion_censos_dias', models.PositiveIntegerField(default=1)),
                ('fecha_campaña', models.DateField()),
                ('duracion_campaña_dias', models.PositiveIntegerField(default=1)),
                ('fecha_votacion', models.DateField()),
                ('duracion_votacion_dias', models.PositiveIntegerField(default=1)),
                ('fecha_recuento', models.DateField()),
                ('duracion_recuento_dias', models.PositiveIntegerField(default=1)),
                ('fecha_publicacion_resultados', models.DateField()),
                ('votacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='censo.votacion')),
            ],
        ),
    ]
