# Generated by Django 5.2.1 on 2026-01-10 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0029_calendariovotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='IdCensoRelacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.censo'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='IdVotacionRelacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.votacion'),
        ),
    ]
