# Generated by Django 5.2.1 on 2026-01-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0030_alter_noticias_idcensorelacionada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_censados', models.PositiveIntegerField()),
                ('total_votos_emitidos', models.PositiveIntegerField()),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('votos_ganadora', models.PositiveIntegerField(default=0)),
                ('fecha_recuento', models.DateTimeField(auto_now_add=True)),
                ('candidatura_ganadora', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censo.candidatura')),
                ('votacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='censo.votacion')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_votos', models.PositiveIntegerField(default=0)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.candidatura')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='censo.resultadovotacion')),
            ],
            options={
                'unique_together': {('resultado', 'candidatura')},
            },
        ),
    ]
